### ISSUE TITLE
Create API Gateway Microservice

### ISSUE THREAD

**Issue by ItamarGronich** [hasadna/open_pension#432]
- [x] Create Node.JS API Gateway microservice. - #436
- [x] Initialize apollo server - #438 
- [x] Setup schema stiching - #438
